[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cartridge-sdk"
description = "GBA SDK — build tool for Game Boy Advance"

version = "1.0.0-rc.1"
dependencies = [
    "click",
    "Pillow"
]

authors = [
  {name = "Lukas Soigneux", email = "lukas.soigneux@epitech.eu"},
]

readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["GBA", "Game Boy", "GameBoy Advance"]

[tool.setuptools.packages.find]
include = ["cartridge*"]

[project.scripts]
cartridge-sdk = "cartridge.cli:main"