[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "cartridge-sdk"
description = "GBA SDK — build tool for Game Boy Advance"

version = "2.0.0"
dependencies = [
    "click",
    "Pillow",
    "pipx"
]

authors = [
  {name = "Lukas Soigneux", email = "lukas.soigneux@epitech.eu"},
]

readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["GBA", "Game Boy", "GameBoy Advance", "Cartridge"]

[tool.setuptools.packages.find]
include = ["cartridge*"]

[project.scripts]
cartridge-sdk = "cartridge.cli:main"