name: Release Stable

on:
  workflow_run:
    workflows:
      ["Cartridge App"]
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-config.json
          manifest-file: .release-manifest.json

      - uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - name: Build & publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pip install build
          python -m build

      - name: Upload to GitHub Release
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} dist/*

      - name: Publish to PyPI
        if: ${{ steps.release.outputs.release_created }}
        uses: pypa/gh-action-pypi-publish@release/v1